# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

theme                    : "minimal-mistakes-hacks-guide"

# Site Settings
title                    : "Hacks Guide"
title_separator          : "-"
name                     : "Nintendo Homebrew"
description              : "Hacks Guide Listings"
url                      : "https://hacks.guide" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
enforce_ssl              : "hacks.guide"
repository               : "hacks-guide/Guide_Landing" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"

# SEO Related
google_site_verification : jVXoPK_-qzKJp4SScnZYpOIX3yDXfGnAoTBJYixUOwg
bing_site_verification   : F3532011519E308583A0A2CAF2DD69E8

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-0R9QL9R7B8"
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Nintendo Homebrew"
  bio              : "Nintendo Homebrew Community"
  location         : "Nullsec"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hacks-guide/Guide_Landing"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/hacks-guide/Guide_Landing"


# Reading Files
include:
  - .htaccess
  - _pages
  - _pages/en_US
exclude: [
  "*.sublime-project",
  "*.sublime-workspace",
  vendor,
  .asset-cache,
  .bundle,
  .jekyll-assets-cache,
  .sass-cache,
  assets/js/plugins,
  assets/js/_main.js,
  assets/js/vendor,
  banner.js,
  Capfile,
  CHANGELOG,
  config,
  Gemfile,
  Gruntfile.js,
  gulpfile.js,
  LICENSE,
  log,
  minimal-mistakes-jekyll.gemspec,
  node_modules,
  package.json,
  package-lock.json,
  Rakefile,
  README,
  tmp,
  rss.py,
  crowdin.yaml,
  staticman.yml,
  _pages/af_ZA,
  # _pages/ar_SA,
  _pages/ca_ES,
  _pages/cs_CZ,
  _pages/da_DK,
  _pages/de_DE,
  _pages/el_GR,
  # _pages/en_PT,
  # _pages/en_US,
  _pages/es_EM,
  # _pages/es_ES,
  _pages/fi_FI,
  # _pages/fr_FR,
  _pages/he_IL,
  _pages/hu_HU,
  _pages/id_ID,
  # _pages/it_IT,
  _pages/ja_JP,
  _pages/ko_KR,
  _pages/ms_MY,
  _pages/no_NO,
  _pages/nl_NL,
  _pages/pl_PL,
  _pages/pt_BR,
  # _pages/pt_PT,
  # _pages/ro_RO,
  # _pages/ru_RU,
  _pages/sr_SP,
  _pages/sv_SE,
  _pages/th_TH,
  _pages/tr_TR,
  _pages/uk_UA,
  _pages/vi_VN,
  # _pages/zh_CN,
  # _pages/zh_TW,
]

markdown_ext: "markdown,mkdown,mkdn,mkd,md,txt"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar: true
  - scope:
      path: "_pages/af_ZA"
      type: pages
    values:
      permalink: /af_ZA/:basename:output_ext
      lang: af
  - scope:
      path: "_pages/ar_SA"
      type: pages
    values:
      permalink: /ar_SA/:basename:output_ext
      lang: ar
  - scope:
      path: "_pages/ca_ES"
      type: pages
    values:
      permalink: /ca_ES/:basename:output_ext
      lang: ca
  - scope:
      path: "_pages/cs_CZ"
      type: pages
    values:
      permalink: /cs_CZ/:basename:output_ext
      lang: cs
  - scope:
      path: "_pages/da_DK"
      type: pages
    values:
      permalink: /da_DK/:basename:output_ext
      lang: da
  - scope:
      path: "_pages/de_DE"
      type: pages
    values:
      permalink: /de_DE/:basename:output_ext
      lang: ds
  - scope:
      path: "_pages/el_GR"
      type: pages
    values:
      permalink: /el_GR/:basename:output_ext
      lang: el
  - scope:
      path: "_pages/en_PT"
      type: pages
    values:
      permalink: /en_PT/:basename:output_ext
      lang: en-PT
  - scope:
      path: "_pages/en_US"
      type: pages
    values:
      permalink: /:basename:output_ext
      lang: en
  - scope:
      path: "_pages/es_ES"
      type: pages
    values:
      permalink: /es_ES/:basename:output_ext
      lang: es
  - scope:
      path: "_pages/fi_FI"
      type: pages
    values:
      permalink: /fi_FI/:basename:output_ext
      lang: fi
  - scope:
      path: "_pages/fr_FR"
      type: pages
    values:
      permalink: /fr_FR/:basename:output_ext
      lang: fr
  - scope:
      path: "_pages/he_IL"
      type: pages
    values:
      permalink: /he_IL/:basename:output_ext
      lang: he
  - scope:
      path: "_pages/hu_HU"
      type: pages
    values:
      permalink: /hu_HU/:basename:output_ext
      lang: hu
  - scope:
      path: "_pages/id_ID"
      type: pages
    values:
      permalink: /id_ID/:basename:output_ext
      lang: id
  - scope:
      path: "_pages/it_IT"
      type: pages
    values:
      permalink: /it_IT/:basename:output_ext
      lang: it
  - scope:
      path: "_pages/ja_JP"
      type: pages
    values:
      permalink: /ja_JP/:basename:output_ext
      lang: ja
  - scope:
      path: "_pages/ko_KR"
      type: pages
    values:
      permalink: /ko_KR/:basename:output_ext
      lang: ko
  - scope:
      path: "_pages/ms_MY"
      type: pages
    values:
      permalink: /ms_MY/:basename:output_ext
      lang: ms
  - scope:
      path: "_pages/no_NO"
      type: pages
    values:
      permalink: /no_NO/:basename:output_ext
      lang: no-NO
  - scope:
      path: "_pages/nl_NL"
      type: pages
    values:
      permalink: /nl_NL/:basename:output_ext
      lang: nl
  - scope:
      path: "_pages/pl_PL"
      type: pages
    values:
      permalink: /pl_PL/:basename:output_ext
      lang: pl
  - scope:
      path: "_pages/pt_BR"
      type: pages
    values:
      permalink: /pt_BR/:basename:output_ext
      lang: pt-BR
  - scope:
      path: "_pages/pt_PT"
      type: pages
    values:
      permalink: /pt_PT/:basename:output_ext
      lang: pt-PT
  - scope:
      path: "_pages/ro_RO"
      type: pages
    values:
      permalink: /ro_RO/:basename:output_ext
      lang: ro
  - scope:
      path: "_pages/ru_RU"
      type: pages
    values:
      permalink: /ru_RU/:basename:output_ext
      lang: ru
  - scope:
      path: "_pages/sr_SP"
      type: pages
    values:
      permalink: /sr_SP/:basename:output_ext
      lang: sr
  - scope:
      path: "_pages/sv_SE"
      type: pages
    values:
      permalink: /sv_SE/:basename:output_ext
      lang: sv
  - scope:
      path: "_pages/th_TH"
      type: pages
    values:
      permalink: /th_TH/:basename:output_ext
      lang: th
  - scope:
      path: "_pages/tr_TR"
      type: pages
    values:
      permalink: /tr_TR/:basename:output_ext
      lang: tr
  - scope:
      path: "_pages/uk_UA"
      type: pages
    values:
      permalink: /uk_UA/:basename:output_ext
      lang: uk
  - scope:
      path: "_pages/vi_VN"
      type: pages
    values:
      permalink: /vi_VN/:basename:output_ext
      lang: vi
  - scope:
      path: "_pages/zh_CN"
      type: pages
    values:
      permalink: /zh_CN/:basename:output_ext
      lang: zh-Hans
  - scope:
      path: "_pages/zh_TW"
      type: pages
    values:
      permalink: /zh_TW/:basename:output_ext
      lang: zh-Hant
  - scope:
      path: "_pages/af_ZA/home.txt"
      type: pages
    values:
      permalink: /af_ZA/index:output_ext
  - scope:
      path: "_pages/ar_SA/home.txt"
      type: pages
    values:
      permalink: /ar_SA/index:output_ext
  - scope:
      path: "_pages/ca_ES/home.txt"
      type: pages
    values:
      permalink: /ca_ES/index:output_ext
  - scope:
      path: "_pages/cs_CZ/home.txt"
      type: pages
    values:
      permalink: /cs_CZ/index:output_ext
  - scope:
      path: "_pages/da_DK/home.txt"
      type: pages
    values:
      permalink: /da_DK/index:output_ext
  - scope:
      path: "_pages/de_DE/home.txt"
      type: pages
    values:
      permalink: /de_DE/index:output_ext
  - scope:
      path: "_pages/el_GR/home.txt"
      type: pages
    values:
      permalink: /el_GR/index:output_ext
  - scope:
      path: "_pages/en_PT/home.txt"
      type: pages
    values:
      permalink: /en_PT/index:output_ext
  - scope:
      path: "_pages/en_US/home.txt"
      type: pages
    values:
      permalink: /index:output_ext
  - scope:
      path: "_pages/es_ES/home.txt"
      type: pages
    values:
      permalink: /es_ES/index:output_ext
  - scope:
      path: "_pages/fi_FI/home.txt"
      type: pages
    values:
      permalink: /fi_FI/index:output_ext
  - scope:
      path: "_pages/fr_FR/home.txt"
      type: pages
    values:
      permalink: /fr_FR/index:output_ext
  - scope:
      path: "_pages/he_IL/home.txt"
      type: pages
    values:
      permalink: /he_IL/index:output_ext
  - scope:
      path: "_pages/hu_HU/home.txt"
      type: pages
    values:
      permalink: /hu_HU/index:output_ext
  - scope:
      path: "_pages/id_ID/home.txt"
      type: pages
    values:
      permalink: /id_ID/index:output_ext
  - scope:
      path: "_pages/it_IT/home.txt"
      type: pages
    values:
      permalink: /it_IT/index:output_ext
  - scope:
      path: "_pages/ja_JP/home.txt"
      type: pages
    values:
      permalink: /ja_JP/index:output_ext
  - scope:
      path: "_pages/ko_KR/home.txt"
      type: pages
    values:
      permalink: /ko_KR/index:output_ext
  - scope:
      path: "_pages/ms_MY/home.txt"
      type: pages
    values:
      permalink: /ms_MY/index:output_ext
  - scope:
      path: "_pages/no_NO/home.txt"
      type: pages
    values:
      permalink: /no_NO/index:output_ext
  - scope:
      path: "_pages/nl_NL/home.txt"
      type: pages
    values:
      permalink: /nl_NL/index:output_ext
  - scope:
      path: "_pages/pl_PL/home.txt"
      type: pages
    values:
      permalink: /pl_PL/index:output_ext
  - scope:
      path: "_pages/pt_BR/home.txt"
      type: pages
    values:
      permalink: /pt_BR/index:output_ext
  - scope:
      path: "_pages/pt_PT/home.txt"
      type: pages
    values:
      permalink: /pt_PT/index:output_ext
  - scope:
      path: "_pages/ro_RO/home.txt"
      type: pages
    values:
      permalink: /ro_RO/index:output_ext
  - scope:
      path: "_pages/ru_RU/home.txt"
      type: pages
    values:
      permalink: /ru_RU/index:output_ext
  - scope:
      path: "_pages/sr_SP/home.txt"
      type: pages
    values:
      permalink: /sr_SP/index:output_ext
  - scope:
      path: "_pages/sv_SE/home.txt"
      type: pages
    values:
      permalink: /sv_SE/index:output_ext
  - scope:
      path: "_pages/th_TH/home.txt"
      type: pages
    values:
      permalink: /th_TH/index:output_ext
  - scope:
      path: "_pages/tr_TR/home.txt"
      type: pages
    values:
      permalink: /tr_TR/index:output_ext
  - scope:
      path: "_pages/uk_UA/home.txt"
      type: pages
    values:
      permalink: /uk_UA/index:output_ext
  - scope:
      path: "_pages/vi_VN/home.txt"
      type: pages
    values:
      permalink: /vi_VN/index:output_ext
  - scope:
      path: "_pages/zh_CN/home.txt"
      type: pages
    values:
      permalink: /zh_CN/index:output_ext
  - scope:
      path: "_pages/zh_TW/home.txt"
      type: pages
    values:
      permalink: /zh_TW/index:output_ext
